"""release user relation

Revision ID: 21dc97e7ff32
Revises: 88f59b7fc857
Create Date: 2021-02-06 17:57:14.240915

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '21dc97e7ff32'
down_revision = '88f59b7fc857'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('release', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_foreign_key('_fk_release_user', 'release', 'user', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('_fk_release_user', 'release', type_='foreignkey')
    op.drop_column('release', 'user_id')
    # ### end Alembic commands ###
