"""add total downloads to package

Revision ID: 88f59b7fc857
Revises: 21a32f52b0c3
Create Date: 2021-02-05 22:10:46.026606

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '88f59b7fc857'
down_revision = '21a32f52b0c3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('package', sa.Column('total_downloads', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('package', 'total_downloads')
    # ### end Alembic commands ###
